name: Run NEORV32 FreeRTOS Demo

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  neorv32-freertos-demo:
    runs-on: ubuntu-latest

    steps:

    - name: '📂 Repository checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: '📦 Install xPack RISC-V GCC 14.2.0'
      run: |
        wget -q https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/releases/download/v14.2.0-2/xpack-riscv-none-elf-gcc-14.2.0-2-linux-x64.tar.gz
        mkdir $GITHUB_WORKSPACE/riscv-gcc
        tar -xzf xpack-riscv-none-elf-gcc-14.2.0-2-linux-x64.tar.gz -C $GITHUB_WORKSPACE/riscv-gcc
        echo $GITHUB_WORKSPACE/riscv-gcc/xpack-riscv-none-elf-gcc-14.2.0-2/bin >> $GITHUB_PATH

    - name: '📦 Install GHDL'
      run: |
        wget -q https://github.com/ghdl/ghdl/releases/download/v4.1.0/ghdl-gha-ubuntu-22.04-mcode.tgz
        mkdir $GITHUB_WORKSPACE/ghdl
        tar -xzf ghdl-gha-ubuntu-22.04-mcode.tgz -C $GITHUB_WORKSPACE/ghdl
        echo $GITHUB_WORKSPACE/ghdl/bin >> $GITHUB_PATH

    - name: '🔍 Check tools'
      run: |
        riscv-none-elf-gcc -v
        ghdl -v

    - name: '⚙️ Run FreeRTOS demo'
      run: /bin/bash -c "chmod u+x $GITHUB_WORKSPACE/demo/sim.sh && $GITHUB_WORKSPACE/demo/sim.sh"
